/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ChocolateFactory;

import org.junit.Test;
import static org.junit.Assert.*;

public class BouilleurChocolatTest {
    @Test 
    public void aNewBouilleurChocolatisEmpty() {
        BouilleurChocolat classUnderTest = BouilleurChocolat.getInstance();
        assertTrue("A new BouilleurChocolat is empty", classUnderTest.estVide());
    }
}
